# Generated by Django 2.2.7 on 2019-12-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='collection',
        ),
    ]
