# Generated by Django 2.2.7 on 2019-12-02 02:07

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(blank=True, upload_to=shop.models.product_image_path_hover, verbose_name='On Hover Preview'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to=shop.models.product_image_path_preview, verbose_name='Product Preview'),
        ),
    ]
