# Generated by Django 2.2.7 on 2019-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191202_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=200, verbose_name="Colors(delim = ', ')"),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price($)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=200, verbose_name="Sizes(delim = ', ')"),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
