# Generated by Django 2.2.7 on 2019-12-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='sizes',
            new_name='size',
        ),
    ]
